name: Report Plugin Build

on:
    workflow_run:
        workflows: ['Plugin Build']

jobs:
    report-build:
        name: Report Plugin Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Publish commit status with the link to download the plugin
              id: plugin_artifact
              uses: Automattic/github-action-report-artifact@v0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  artifact-name: sensei-lms-${{ github.event.workflow_run.head_sha }}
                  report-on: commit_status
                  context: Plugin Build Download
                  message: Click on "Details" to download the plugin zip file
            - name: Publish comment with playground link
              id: plugin_artifact
              uses: Automattic/github-action-report-artifact@v0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  report-on: pull_request
                  ignore-empty: 'true'
                  message: |
                    Howdy! Here's the list of plugin zip files to download, based on the commit {{ context.sha }}:
                    
                    {{#each list}}
                    - [{{ name }}.zip]({{url}});
                    {{/each}}
